### ISSUE TITLE
sassVariablesHelper.route -- where should this route start?

### ISSUE THREAD

**Issue by lukenconsulting** [Nkzq/sass-variables-helper#12]
In the documentation there is the following:

After you installed the extension, you have to specify the sass file you want to explore in your workspace settings, like so :
"sassVariablesHelper.route": "/css/root/vars/_colors.scss"

 "/css/root/vars/_colors.scss" -- what is this relative to? I am using an ANgular project and the scss folder is located here:

/Users/dennisluken/Documents/Projects/BKNorth/bknorth/angular-src/src/sass/abstracts/_variables.scss

What value do I use for the "sassVariablesHelper.route": "__________???________/_variables.scss"

what should __________???________/ be given the full absolute path given above?

thanks!

**Comment by Nkzq** [comment]
Hi @lukenconsulting,

Sorry for the late answer.
If your workspace contains a single folder, it's a relative path starting from your workspace root.
If you have multiple folders, you have to provide an absolute path.

Tell me if this clear and working for you 😃 

Best.

**Comment by Nkzq** [comment]
There is the clarification about your issue on the VSCode Marketplace :
- A Visual Studio Code "workspace" is the collection of one or more folders that are opened in a VS Code window (instance).
- So, if you have opened multiple projects in the same VSCode window, you have to provide an absolute path to your sass file, like you mentioned above : `/Users/dennisluken/Documents/Projects/BKNorth/bknorth/angular-src/src/sass/abstracts/_variables.scss`
- For a single folder, simply use a relative path starting from your project, probably something like : `/bknorth/angular-src/src/sass/abstracts/_variables.scss` in your case.

**Comment by lukenconsulting** [comment]
Thank you for the clarification, unfortunately it is still not working. Here is the property/value in my settings json for vs code:

"sassVariablesHelper.route": "/Users/dennisluken/Documents/Projects/weed/projectgreen/styles/base/colors.scss"

Also, when I try click on the refresh icon I get this error: 

command 'sassVariables.refreshEntry' not found

**Comment by Nkzq** [comment]
It seems the plugin ran into an old dependency issue.
It's has been patched ! Should work now.
