### ISSUE TITLE
Path fails if leading slash is omitted

### ISSUE THREAD

**Issue by garrettw** [Nkzq/sass-variables-helper#2]
It would be nice if this extension would automatically prepend a slash to the configured route if it doesn't have one.

**Comment by Nkzq** [comment]
Thanks for you report @garrettw, I'll take a look asap 😃

**Comment by Nkzq** [comment]
There is a fix : https://github.com/Nkzq/sass-variables-helper/commit/c73863f1e8a6e7fe60e178cfc1d56148c60ab6f3
Let me know if it works for you !

**Comment by garrettw** [comment]
It seems to work. Thanks :)
