### ISSUE TITLE
No variables in empty workspace

### ISSUE THREAD

**Issue by annabranco** [Nkzq/sass-variables-helper#3]
Hi.
I really like the idea of this helper, but it just doesn't seem to work on my VSCode.
I'm trying to read variables from different projects, and I've tried so many different ways of describing my variables route, but I always get the message "_No variables in empty workspace_".

Is there any known bug that could cause this issue? Any suggestions for me?

Thanks!

**Comment by Nkzq** [comment]
Hi @annabranco,

It seems there in an error coming from your SASS file path or your workspace settings.
Could you copy your workspace settings.json and a screenshot that shows the treeview of your project ?

Thanks.

**Comment by annabranco** [comment]
Hi @Nkzq 
Thanks for you answer and sorry for taking too long.
That's the screenshow where you can see both the treeview and Workspace settings.
![image](https://user-images.githubusercontent.com/39792862/49583121-767a5600-f957-11e8-9b10-c1779d9d48d3.png)

**Comment by Nkzq** [comment]
Your `settings.json` file seems good. Can I have a copy of your `_variables.scss` files please ? I'm gonna investigate this week-end.

**Comment by annabranco** [comment]
Okay. Thank you!!

Here is my `_variables.scss`
```
//COLORS
$nipiter-green     : #158C3F;
$green             : #048e3c;
$light-green       : #C4E2CF;
$nipiter-red       : #e11b1c;
$dark-red          : #a11b1b;
$black             : #000000;
$dark-gray         : #4c4c4c;
$gray              : #e4e4e4;
$white             : #ffffff;
$transparent-white : rgba(255, 255, 255, 0.59);
$feminist-purple   : #2a1736;

$yellow        : #ffff73;
$twitter-blue  : #5a8dbd;
$facebook-blue : #184f83;

// font-family
@import url('https://fonts.googleapis.com/css?family=Averia+Sans+Libre|Averia+Serif+Libre|Barlow');
$title    : 'Barlow',             sans-serif;
$subtitle : 'Averia Sans Libre',  sans-serif;
$main     : 'Averia Serif Libre', serif;

// horizontal padding/margin for formats
$size--320   : 31px;
$size--768   : 90px;
$size--1200  : 140px;
$width--1200 : calc(100% - 177px - 397px);

// sizes of main components
$header__height : 77px;
$footer__height : 69px;
$main__height   : calc( 100vh - #{$header__height} - #{$footer__height} );

// styles
@mixin font-h1 {
  font-family : $title;
  font-size   : 50px;
  font-weight : 600;
  line-height : 1.2;
  color       : $transparent-white;
}

@mixin font-h1--1200 {
  font-size   : 80px;
  line-height : 0.25;
}

@mixin font-h2 {
  font-family : $title;
  font-size   : 18px;
  font-weight : 600;
  line-height : 0.78;
  color       : $nipiter_green;
}

@mixin font-h2--1200 {
  font-size   : 21px;
  line-height : 0.67;
}

@mixin font-h3 {
  font-family : $subtitle;
  font-size   : 14px;
  font-weight : bold;
  line-height : 1;
  color       : $nipiter_green;
}

@mixin font-h3--1200 {
  font-size   : 20px;
  line-height : 0.7;
}

@mixin font-h4 {
  font-family : $subtitle;
  font-size   : 18px;
  font-weight : bold;
  line-height : 1.67;
  color       : $dark-red;
}

@mixin font-h4--1200 {
  font-size   : 30px;
  line-height : 1;
}

@mixin font-button {
  font-size   : 16px;
  line-height : 0.88;
}

@mixin font-button--768 {
  font-size   : 24px;
  line-height : 0.58;
}

@mixin font-button--1200 {
  font-size   : 30px;
  line-height : 0.47;
}

@mixin font-p {
  font-family : $main;
  font-size   : 14px;
  font-weight : bold;
  line-height : 2.14;
  color       : $dark-gray;
}

@mixin font-p--1200 {
  font-size   : 18px;
  line-height : 1.67;
}

@mixin font-dorsal {
  font-family : $title;
  font-size   : 18.5px;
  font-weight : 600;
  line-height : 1.35;
  color       : $white;
}

@mixin font-footer {
  font-family : $title;
  font-size   : 10px;
  font-weight : 500;
  line-height : 1.6;
  color       : $white;
}
```

**Comment by sapkra** [comment]
I have the same problem...have you find out something?

**Comment by Nkzq** [comment]
Hey there,

I didn't manage to reproduce your issue. I got a new issue with files that not only contains color variables.
Regarding your issue, a coworker had the same problem and he managed to fix it by desactivate and reactivate the plugin ... hope it helps.

**Comment by Nkzq** [comment]
Hey @sapkra @annabranco, any update ?

**Comment by sapkra** [comment]
I installed the plugin again and it is still not working.
I'm just getting the error `Cannot read property '0' of null`.

Maybe it will help to add better error messages and checks so that it will be easier to debug problems with this plugin like `Cannot find file at <FULL_PATH>`.

**Comment by Nkzq** [comment]
Hey @sapkra, I did an update few months ago. You have to wrap your colors variables between comments like this :
```scss
// COLORS
.....
// END COLORS
```

**Comment by annabranco** [comment]
@Nkzq Great! It now works! Thanks!! 😊

**Comment by Nkzq** [comment]
You are welcome @annabranco, I close the issue then 😉
