### ISSUE TITLE
Cannot read property trim of undefined

### ISSUE THREAD

**Issue by rodrigoAbril** [Nkzq/sass-variables-helper#4]
Cant get it to work, if i set the "sassVariablesHelper.route" i always get this error
```
Cannot read property trim of undefined
```

**Comment by Nkzq** [comment]
Hi @rodrigoAbril,

Sorry for the late answer.
May I have a copy of your `settings.json`file and additionally your sass variables files please ?
Thanks.

**Comment by Nkzq** [comment]
Hi @rodrigoAbril,

It seems there was an issue if the variable file contains not only colors.
I did commit a fix, please check the updated README 😀

**Comment by rodrigoAbril** [comment]
Thanks Dude, sorry for not replying earlier, ill try your fix and ill publish the results here

**Comment by Nkzq** [comment]
Hey @rodrigoAbril, any update ?

**Comment by rodrigoAbril** [comment]
Hi @Nkzq 
I tried the // COLORS // END COLORS comments, I dont got the error anymore but my color list is still empty

**Comment by Nkzq** [comment]
Hi @rodrigoAbril,
Can you give me more details about your working environment ?

**Comment by rodrigoAbril** [comment]
@Nkzq thanks its all good! Working on all my environments.
I used the def functionality to get the relative path of the file and that was missing the '/' at the beginning of it.
