### ISSUE TITLE
Copy variables not work

### ISSUE THREAD

**Issue by if540** [Nkzq/sass-variables-helper#5]
Hi.
i try click variable
show Variable copied to clipboard
but clipboard is empty
Has anyone experienced the same problem?

**Comment by Nkzq** [comment]
Hi @if540,

I can paste the variable after clicked on it with no problem ... Can you give me more details about your 
working environment ?

**Comment by if540** [comment]
VScode: 1.32.3 (user setup)
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
