### ISSUE TITLE
Multi-root workspace issue

### ISSUE THREAD

**Issue by krisdr** [Nkzq/sass-variables-helper#7]
Hello, and thank you for this great extension !
It works fine for a workspace with a single project (by adding the route and the comments), but I have troubles to make it work with a multi-root workspace.
Is your extension compatible with that kind of workspace ?
Many thanks !

**Comment by krisdr** [comment]
I did a pull request 2 weeks ago to fix this case : https://github.com/Nkzq/sass-variables-helper/pull/8
@Nkzq Did you see it ?

**Comment by kamirura** [comment]
What should the path look like when I want to use one file for multiple projects?

"sassVariablesHelper.route": "C:/projects/projectname/scss/_colors.scss"   that doesnt seem to work? Should I be using something else?

**Comment by Nkzq** [comment]
Hello, sorry. for the late answer. I did some update, if you have multi-root workspace you can now provide an absolute path to your variables file.

Best.
